API_KEY="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"
WATSONX_API = "HHcYAno-kO-6LY1lJGBPrgTAx_gH_gBWM0Rp6imVa7eA"
PROJECT_ID= "8c4cdab3-8dad-4aa3-aa2f-bb056d48e036"
BAM_API = "pak-L4W1dYqalPWtiFeLM1EkTRKqSQ-vRbFl8mAAfnWC8fc"
GRANITE_1= "ibm/granite-13b-instruct-v1"
GRANITE_2= "ibm/granite-13b-instruct-v2"